hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${xpname}-${now:%H-%M-%S}
  callbacks:
    LogJobReturnCallback:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback

entrypoints: ???
xpname: ???

defaults:
  - xp: ???
  - _self_
